platform :ios, '10.0'

target 'RAC+MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC+MVVM
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'Masonry', '~> 1.1.0'

end
